shops:
  建材铺:
    - "GRASS_BLOCK:32"
    - "STONE:32"
    - "COBBLESTONE:32"
    - "DIRT:32"
    - "SAND:32"
    - "COBBLED_DEEPSLATE:32"
    - "ANDESITE:16"
    - "GRANITE:16"
    - "DIORITE:16"
    - "CLAY:32"
    - "BLACKSTONE:16"
    - "DARK_PRISMARINE:16"
    - "GLASS:16"
    - "ICE:16"
    - "SCAFFOLDING:16"
    - "QUARTZ_BLOCK:16"
    - "PRISMARINE:16"
    - "CALCITE:16"
    - "TERRACOTTA:16"
    - "OCHRE_FROGLIGHT:8"
    - "PEARLESCENT_FROGLIGHT:8"
    - "VERDANT_FROGLIGHT:8"
    - "SEA_LANTERN:8"
    - "END_ROD:8"
    - "MAGMA_BLOCK:8"
    - "RED_SAND:32"
    - "GRAVEL:32"
    - "SMOOTH_QUARTZ:16"
    - "OBSIDIAN:6"
  农贸商:
    - "COOKED_BEEF:16"
    - "COOKED_CHICKEN:16"
    - "COOKED_COD:16"
    - "COOKED_MUTTON:16"
    - "BREAD:16"
    - "BROWN_MUSHROOM:16"
    - "RED_MUSHROOM:16"
    - "MOSS_BLOCK:16"
    - "HONEY_BOTTLE:16"
    - "ACACIA_SAPLING:8"
    - "BAMBOO:8"
    - "OAK_SAPLING:8"
    - "BIRCH_SAPLING:8"
    - "CHERRY_SAPLING:8"
    - "DARK_OAK_SAPLING:8"
    - "JUNGLE_SAPLING:8"
    - "SPRUCE_SAPLING:8"
    - "SWEET_BERRIES:16"
    - "MELON_SEEDS:4"
    - "PUMPKIN_SEEDS:4"
    - "WHEAT_SEEDS:4"
    - "SUGAR_CANE:4"
    - "CARROT:4"
    - "POTATO:4"
    - "BEETROOT_SEEDS:4"
    - "NETHER_WART:4"
    - "GLOW_BERRIES:4"
  木料铺:
    - "ACACIA_LOG:8"
    - "BIRCH_LOG:8"
    - "CHERRY_LOG:8"
    - "DARK_OAK_LOG:8"
    - "JUNGLE_LOG:8"
    - "OAK_LOG:8"
    - "SPRUCE_LOG:8"
    - "CRIMSON_STEM:8"
    - "WARPED_STEM:8"
    - "MANGROVE_ROOTS:8"
    - "MANGROVE_LOG:8"
    - "PALE_OAK_LOG:8"
    - "BAMBOO_BLOCK:8"
    - "STRIPPED_ACACIA_LOG:8"
    - "STRIPPED_BIRCH_LOG:8"
    - "STRIPPED_CHERRY_LOG:8"
    - "STRIPPED_DARK_OAK_LOG:8"
    - "STRIPPED_JUNGLE_LOG:8"
    - "STRIPPED_OAK_LOG:8"
    - "STRIPPED_SPRUCE_LOG:8"
    - "STRIPPED_CRIMSON_STEM:8"
    - "STRIPPED_WARPED_STEM:8"
    - "STRIPPED_MANGROVE_LOG:8"
    - "STRIPPED_PALE_OAK_LOG:8"
    - "STRIPPED_BAMBOO_BLOCK:8"
    - "DARK_OAK_LEAVES:8"
    - "OAK_LEAVES:8"
    - "SPRUCE_LEAVES:8"
    - "JUNGLE_LEAVES:8"
    - "ACACIA_LEAVES:8"
    - "AZALEA_LEAVES:8"
    - "FLOWERING_AZALEA_LEAVES:8"
    - "PALE_OAK_LEAVES:8"
    - "CHERRY_LEAVES:8"
    - "MANGROVE_LEAVES:8"
    - "BIRCH_LEAVES:8"
  加工铺:
    - "OAK_STAIRS:16"
    - "SPRUCE_STAIRS:16"
    - "BIRCH_STAIRS:16"
    - "ACACIA_STAIRS:16"
    - "DARK_OAK_STAIRS:16"
    - "BAMBOO_STAIRS:16"
    - "CRIMSON_STAIRS:16"
    - "WARPED_STAIRS:16"
    - "STONE_BRICK_STAIRS:16"
    - "SANDSTONE_STAIRS:16"
    - "RED_SANDSTONE_STAIRS:16"
    - "COBBLESTONE_STAIRS:16"
    - "BRICK_STAIRS:16"
    - "NETHER_BRICK_STAIRS:16"
    - "QUARTZ_STAIRS:16"
    - "POLISHED_GRANITE_STAIRS:16"
    - "POLISHED_DIORITE_STAIRS:16"
    - "POLISHED_ANDESITE_STAIRS:16"
    - "DEEPSLATE_BRICK_STAIRS:16"
    - "DEEPSLATE_TILE_STAIRS:16"
    - "PRISMARINE_STAIRS:16"
    - "PRISMARINE_BRICK_STAIRS:16"
    - "DARK_PRISMARINE_STAIRS:16"
    - "BLACKSTONE_STAIRS:16"
    - "POLISHED_BLACKSTONE_BRICK_STAIRS:16"
    - "POLISHED_BLACKSTONE_STAIRS:16"
    - "OAK_SLAB:32"
    - "SPRUCE_SLAB:32"
    - "BIRCH_SLAB:32"
    - "ACACIA_SLAB:32"
    - "DARK_OAK_SLAB:32"
    - "BAMBOO_SLAB:32"
    - "CRIMSON_SLAB:32"
    - "WARPED_SLAB:32"
    - "STONE_BRICK_SLAB:32"
    - "SANDSTONE_SLAB:32"
    - "RED_SANDSTONE_SLAB:32"
    - "COBBLESTONE_SLAB:32"
    - "BRICK_SLAB:32"
    - "NETHER_BRICK_SLAB:32"
    - "SMOOTH_QUARTZ_SLAB:32"
    - "POLISHED_GRANITE_SLAB:32"
    - "POLISHED_DIORITE_SLAB:32"
    - "POLISHED_ANDESITE_SLAB:32"
    - "DEEPSLATE_BRICK_SLAB:32"
    - "DEEPSLATE_TILE_SLAB:32"
    - "PRISMARINE_SLAB:32"
    - "PRISMARINE_BRICK_SLAB:32"
    - "DARK_PRISMARINE_SLAB:32"
    - "BLACKSTONE_SLAB:32"
    - "POLISHED_BLACKSTONE_BRICK_SLAB:32"
    - "POLISHED_BLACKSTONE_SLAB:32"
    - "COBBLED_DEEPSLATE_SLAB:32"
    - "BAMBOO_MOSAIC_SLAB:32"
  土坊:
    - "WHITE_CONCRETE:8"
    - "ORANGE_CONCRETE:8"
    - "MAGENTA_CONCRETE:8"
    - "LIGHT_BLUE_CONCRETE:8"
    - "YELLOW_CONCRETE:8"
    - "LIME_CONCRETE:8"
    - "PINK_CONCRETE:8"
    - "GRAY_CONCRETE:8"
    - "LIGHT_GRAY_CONCRETE:8"
    - "CYAN_CONCRETE:8"
    - "PURPLE_CONCRETE:8"
    - "BLUE_CONCRETE:8"
    - "BROWN_CONCRETE:8"
    - "GREEN_CONCRETE:8"
    - "RED_CONCRETE:8"
    - "BLACK_CONCRETE:8"
    - "WHITE_TERRACOTTA:8"
    - "ORANGE_TERRACOTTA:8"
    - "MAGENTA_TERRACOTTA:8"
    - "LIGHT_BLUE_TERRACOTTA:8"
    - "YELLOW_TERRACOTTA:8"
    - "LIME_TERRACOTTA:8"
    - "PINK_TERRACOTTA:8"
    - "GRAY_TERRACOTTA:8"
    - "LIGHT_GRAY_TERRACOTTA:8"
    - "CYAN_TERRACOTTA:8"
    - "PURPLE_TERRACOTTA:8"
    - "BLUE_TERRACOTTA:8"
    - "BROWN_TERRACOTTA:8"
    - "GREEN_TERRACOTTA:8"
    - "RED_TERRACOTTA:8"
    - "BLACK_TERRACOTTA:8"
    - "WHITE_GLAZED_TERRACOTTA:8"
    - "ORANGE_GLAZED_TERRACOTTA:8"
    - "MAGENTA_GLAZED_TERRACOTTA:8"
    - "LIGHT_BLUE_GLAZED_TERRACOTTA:8"
    - "YELLOW_GLAZED_TERRACOTTA:8"
    - "LIME_GLAZED_TERRACOTTA:8"
    - "PINK_GLAZED_TERRACOTTA:8"
    - "GRAY_GLAZED_TERRACOTTA:8"
    - "LIGHT_GRAY_GLAZED_TERRACOTTA:8"
    - "CYAN_GLAZED_TERRACOTTA:8"
    - "PURPLE_GLAZED_TERRACOTTA:8"
    - "BLUE_GLAZED_TERRACOTTA:8"
    - "BROWN_GLAZED_TERRACOTTA:8"
    - "GREEN_GLAZED_TERRACOTTA:8"
    - "RED_GLAZED_TERRACOTTA:8"
    - "BLACK_GLAZED_TERRACOTTA:8"
  染坊:
    - "WHITE_DYE:8"
    - "ORANGE_DYE:8"
    - "MAGENTA_DYE:8"
    - "LIGHT_BLUE_DYE:8"
    - "YELLOW_DYE:8"
    - "LIME_DYE:8"
    - "PINK_DYE:8"
    - "GRAY_DYE:8"
    - "LIGHT_GRAY_DYE:8"
    - "CYAN_DYE:8"
    - "PURPLE_DYE:8"
    - "BLUE_DYE:8"
    - "BROWN_DYE:8"
    - "GREEN_DYE:8"
    - "RED_DYE:8"
    - "BLACK_DYE:8"
    - "WHITE_WOOL:16"
    - "ORANGE_WOOL:16"
    - "MAGENTA_WOOL:16"
    - "LIGHT_BLUE_WOOL:16"
    - "YELLOW_WOOL:16"
    - "LIME_WOOL:16"
    - "PINK_WOOL:16"
    - "GRAY_WOOL:16"
    - "LIGHT_GRAY_WOOL:16"
    - "CYAN_WOOL:16"
    - "PURPLE_WOOL:16"
    - "BLUE_WOOL:16"
    - "BROWN_WOOL:16"
    - "GREEN_WOOL:16"
    - "RED_WOOL:16"
    - "BLACK_WOOL:16"
    - "WHITE_STAINED_GLASS:16"
    - "ORANGE_STAINED_GLASS:16"
    - "MAGENTA_STAINED_GLASS:16"
    - "LIGHT_BLUE_STAINED_GLASS:16"
    - "YELLOW_STAINED_GLASS:16"
    - "LIME_STAINED_GLASS:16"
    - "PINK_STAINED_GLASS:16"
    - "GRAY_STAINED_GLASS:16"
    - "LIGHT_GRAY_STAINED_GLASS:16"
    - "CYAN_STAINED_GLASS:16"
    - "PURPLE_STAINED_GLASS:16"
    - "BLUE_STAINED_GLASS:16"
    - "BROWN_STAINED_GLASS:16"
    - "GREEN_STAINED_GLASS:16"
    - "RED_STAINED_GLASS:16"
    - "BLACK_STAINED_GLASS:16"
